### ISSUE TITLE
Build error on Raspberry Pi 4: objcopy: architecture i386 unknown

### ISSUE THREAD

**Issue by vatbrain** [TytanRock/PenguinTuner#11]
Hello,
I was referred here by CTRE support. I realize it is unsupported.
I was told the intent was to support linux.  On which microprocessor(s) was not clear. 
I was hoping this meant Raspberry Pi, but I can see now how this may be problematic as the functionality depends upon a pre-compiled backend.
I am trying to build this on a Raspberry Pi 4. Cloned repository. Ran config.sh. When running build.sh, get the following error:
objcopy: architecture i386 unknown.
Here is the complete build output:
pi@rpi401wrkbnch:~/Documents/ctre/PenguinTuner $ ./build.sh
version: 0.3.1
-- Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.64.0") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Documents/ctre/PenguinTuner/build
Scanning dependencies of target PenguinTuner
[ 16%] Building C object CMakeFiles/PenguinTuner.dir/native/src/app_callbacks.c.o
[ 33%] Building C object CMakeFiles/PenguinTuner.dir/native/src/application.c.o
[ 50%] Building C object CMakeFiles/PenguinTuner.dir/native/src/can_devices.c.o
[ 66%] Building C object CMakeFiles/PenguinTuner.dir/native/src/robot_controller.c.o
[ 83%] Building C object CMakeFiles/PenguinTuner.dir/resources.c.o
[100%] Linking C executable PenguinTuner
objcopy: architecture i386 unknown
make[2]: *** [CMakeFiles/PenguinTuner.dir/build.make:147: PenguinTuner] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/PenguinTuner.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

So it looks like this may not be intended for an arm processor? If that is the case, I'm not sure what the "cross platform" in the readme really means. Could you please clarify?  Any information would be greatly appreciated.
I am able to run phoenix tuner on a windows PC networked to a raspberry pi which is connected to a CTRE controller using socketCAN and a usb-to-CAN adapter, but I was hoping to be able to run something roughly equivalent to tuner native on the raspberry pi to eliminate the use of a windows PC. Thanks!

**Comment by TytanRock** [comment]
Hello,
I'm sorry for the confusion, I want this to be cross-platform which includes raspberry pi, Windows, and MacOS, but haven't gotten to that point yet. So far I've been testing and developing on the amd64 architecture in Debian.
I also haven't been working on this very much lately since school started, so I can't give you an ETA on when you can expect raspberry pi support. But I could cross-compile the backend for raspberry pi for you and it *may* work.

Also bear in mind that this application is **very** barebones, and may not suit your needs at this moment. It contains the necessary tools to get up and running, which includes changing device ID's, device names, blinking, firmware updating, and factory defaulting to clear the FRC Lock, all of which is typically performed once on setup and never again.

Hope this helps, let me know if you have any other questions or want to try the cross-compiled backend.

**Comment by vatbrain** [comment]
No problem at all. I told the people at CTRE I would like to be able to do simple things like changing the CAN ID and updating the firmware directly in linux, without an extra WIndows PC (I'm using their controllers on linux with socketCAN) and they gave me the link here so I thought I'd give it a try. I can accomplish what I need to using the mainstream method. If you have a chance and are interested in me trying to make it work on a Raspberry Pi, I am certainly willing to give it a try, but no hurry. Focus on your school. Thank you for the response!

**Comment by TytanRock** [comment]
@vatbrain 
Check out the branch https://github.com/TytanRock/PenguinTuner/tree/genericized-resource-embedder
and insert the shared object I zipped below under the `backend/lib` directory. It should at least compile, and I've tested to make sure it displays when I'm rdp'd to my pi, I haven't yet checked to see if it actually communicates with the diagnostic server. 

If it works on your end I'll work on adding raspberry pi so it automatically picks any updates I add to this project.

[raspberry_pi_backend.zip](https://github.com/TytanRock/PenguinTuner/files/5382231/raspberry_pi_backend.zip)

**Comment by vatbrain** [comment]
@TytanRock 
I did as you outlined above, and I am able to build successfully.
I am able to run the app using ./runApp.sh, 
I assume I am supposed to choose localhost as the Server Address since I am running on the raspberry pi that is connected to the USB-to-CAN device.

When I run the Phoenix-Linux-SocketCAN-Example on the pi (which has been modified to instantiate its own diagnostic server from the library by commenting out a line of code) and then switch to the "CAN Devices", I can see my VictorSPX and take a Self-Test Snapshot, which looks sane. 
**Cool!**

If I am NOT running the Phoenix-Linux-SocketCAN-Example on the pi:
When I go to the "CAN Devices" tab, I do not see my VictorSPX which is connected to the network.
When I go back to the Robot Controller tab, and click "Run Temporary Diagnostic Server", I get a "Hello World!" in the Penguin Tuner Window, but no change in results when I switch back to the CAN Devices tab.
This is pretty much what I would expect, but I am not certain whether it ought to be.

This is great! I have some more motor controllers to set up, and will attempt to set their node addresses and update their firmware (unless you recommend otherwise as I don't want to risk bricking them :) ) using this, and report back after I have attempted it.
Thank you very much!

**Comment by TytanRock** [comment]
Yep, the `run temporary diagnostic server` button doesn't work yet, I should make that more clear.
I also need to remove the temporary devices that you see when starting the program without connecting to a diagnostic server, these things were to ensure the GUI was working early on but aren't needed anymore.

You should be fine with firmware upgrading/setting ID's. The firmware upgrade isn't very stable, but that just means it may fail sometimes, no risk to bricking as far as I can tell.

Glad to hear it's working, though! I'll definitely get on adding raspberry pi to the build script so it's packaged and everything for you and anyone else using the pi.

I'll close this issue once raspberry pi is added to the build script.

**Comment by vatbrain** [comment]
To follow up, I was able to successfully change the node address of a new controller with the latest changes, but I was unable to update the firmware. I tried multiple times, but there was no indication of any problem or progress after trying to initiate a controller update.  I don't understand the philosophy of having to run a separate diagnostic server somewhere in order to be able to use the tuner apps. It would be much more straightforward if the tuner apps provided the functionality necessary to interface with controllers directly.

**Comment by TytanRock** [comment]
Regarding your firmware upgrade problems, it may be caused either by the instability of firmware upgrading using Penguin Tuner, or it may be related to your SocketCAN device. An easy test is to try firmware upgrading using Phoenix Tuner, which implements it in a more robust way(a way that Penguin Tuner will eventually implement as well, but requires a decent bit of complexity), and see if it succeeds or fails. If Phoenix Tuner runs into the same issues, it's probably related to your SocketCAN device, but the folks at CTRE support will be better able to guide you. Otherwise, it's related to Penguin Tuner's implementation which will be handled in a future update.

The reason for the Tuner apps interfacing with a diagnostic server as opposed to interfacing directly with your SocketCAN is largely because of the FRC market and specific applications where the robot controller runs headless. This means I can't rely on the Penguin Tuner application running on the robot controller. If I did, I would exclude a relatively large population that I was intending to target, FRC software teams that run Non-Windows OS's.
As well as that, the diagnostic server is handled and supported by CTRE, and is too complex for me to re-implement at this time. I'd much rather use their supported software to ease some of the support on my end.

Just as an FYI, diagnostic server is an HTTP server running on port 1250 which you can interact with by sending HTTP Get requests using CURL or any browser. An example request is `http://localhost:1250/?action=getdevices`, which is far simpler than interfacing with SocketCAN, sending out whatever CAN frames are necessary to get all the devices, and interpreting them. That's how most of this is handled in the backend, CURL requests to the server and parsing the JSON responses.

**Comment by vatbrain** [comment]
I did the firmware upgrade using Phoenix Tuner from a Windows PC. Once I get Phoenix Tuner recognizing my CAN device, which usually involves one or more re-boots, it works smoothly. Like I have said previously, the interface between the client and the remote device does not seem robust. I am unable to start and stop the Phoenix diagnostic server on the pi from the windows host.  It does not detect or report any problems, it just does not seem to work.  It may be some sort of permission problem.

**Comment by TytanRock** [comment]
If you're having issues with the Pi interfacing with Phoenix Tuner, that's definitely something CTRE can help with. I'm sure they want to improve Phoenix Tuner with Linux remote platforms as much as possible. I know from my experience as well as many others experience that it interfaces well with FRC's RoboRIO, so I don't see why it can't work well with the Pi also.

**Comment by TytanRock** [comment]
Sorry for the wait, but Cross-Compile is now automated and works, tested from my raspberry pi 3 B+.
I'll probably pick up the other PR and publish another release that includes the armhf.deb sometime this week.
