### ISSUE TITLE
Move button to initiate a self-test from the bottom of the self-test window to the top.

### ISSUE THREAD

**Issue by vatbrain** [TytanRock/PenguinTuner#31]
When running self-tests on several different devices, it is necessary to repeatedly move the focus to the top of the window to select a new device, and then move it to the bottom of the window to run the self-test, then repeat the top to bottom to top motion for additional devices. It would be better if all of the command buttons were near the top of the window to minimize the required mouse movements if this is possible.

**Comment by TytanRock** [comment]
I think the general flow of the application should be that the top of the application holds controls that aren't used often with data that's section-dependent. Bottom of the screen should hold controls that are used often with data that's always relevant.
So, I think to cover your use case of switching between devices repeatedly while using self-test, I'll change the selected device label to a combobox, so that you can change your device without ever swapping off the self-test screen.
This has the added effect of changing the device regardless of what tab you're on, which will be useful for future tabs, such as configs.
It also matches Phoenix Tuner a little better, the controls are in the same place with the selected device shown as a combobox along with the highlighted device in CAN Devices.

What do you think? Will that cover your use case?

**Comment by TytanRock** [comment]
I've drafted a candidate fix on the [combobox-deviceselection](https://github.com/TytanRock/PenguinTuner/tree/combobox-deviceselection) branch. Still have to test with multiple devices, but I should be able to do that on Monday. Looks like this:
![image](https://user-images.githubusercontent.com/13025939/109406632-ace18880-7948-11eb-84b6-b913ec51fc93.png)

If this is sufficient let me know, otherwise please explain in greater detail why moving control buttons to the top is a better solution than changing the device in the lower left.

**Comment by TytanRock** [comment]
I'm going to close this issue now after it being inactive and having merged in a feature that may fix this.
